<?xml version="1.0" encoding="utf-8"?><Database Name="PersonnelDepartmentDB" Class="DataEmployeeDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=&quot;C:\Users\Анастасия\Desktop\БизАпс\Тестовое задание\Тестовое задание\App_Data\PersonnelDepartmentDB.mdf&quot;;Integrated Security=True" SettingsObjectName="DBHelper.Properties.Settings" SettingsPropertyName="PersonnelDepartmentDBConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Employee" Member="Employee">
    <Type Name="Employee">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MiddleName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Role" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="ChiefId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Division" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>